### ISSUE TITLE
Providers and products should not be deletable

### ISSUE THREAD

**Issue by blimpich** [WhitmanCSCapstone/bmac-warehouse#205]
Since deleting either could cause a lot of issues with data integrity I think that this should not be an option anymore, only shipments and receipts should be deletable.

**Comment by milloypr** [comment]
Removed for both. Should consider asking Jeff if he ever needs to remove Providers or Products, given that there are multiple similar products it could be something he'd want to do. For the time being, neither are now deletable.

**Comment by blimpich** [comment]
not currently in master so I'm gonna reopen this for clarity's sake

**Comment by JulesChoq** [comment]
@milloypr

**Comment by blimpich** [comment]
@JulesChoq are you at-ing Paul because you were thinking of taking this issue?
