### ISSUE TITLE
Add "Material Number" field to Product information

### ISSUE THREAD

**Issue by milloypr** [WhitmanCSCapstone/bmac-warehouse#214]

**Comment by blimpich** [comment]
column should be available in both the product table and in the invoice

**Comment by blimpich** [comment]
Update from Jeff: "Everywhere the product name is displayed the material code should also show.  In the shipments tab I would like to be able to search for the code.  Same for receipts.  The number should show on Invoices/receipts. Inventory Reports is especially critical for the code to show.  So yeah, I think anywhere the product name appears the code should also appear."
