### ISSUE TITLE
Add column for sum of total weights of shipments for each Customer in Inventory Shipments report

### ISSUE THREAD

**Issue by milloypr** [WhitmanCSCapstone/bmac-warehouse#215]

**Comment by milloypr** [comment]
This need only appear in the CSV and does not need to be a part of the displayed table.

**Comment by blimpich** [comment]
for auto-totalling, he only cares about total weight being totaled, not billed amt, but its not necessary for him to transfer between apps

**Comment by blimpich** [comment]
eact table aggregated cells might be an easy way of doing this??? [link](https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/archives/v6-examples/react-table-100k-rows-aggregation))
