### ISSUE TITLE
Remove and replace DatePicker component 

### ISSUE THREAD

**Issue by milloypr** [WhitmanCSCapstone/bmac-warehouse#219]
Using this component has been a headache for Jeff. It is not intuitive to select the date range. Would probably be best to separate picking the start and end date and only show one calendar for each at a time. However, since this is not a critical issue, we can push it back until after the soft launch has been started, though I don't think this should be underestimated as a usability problem when it is a core function of the system.

**Comment by blimpich** [comment]
Two date pickers rather than one date range component should be fairly easy to implement
