### ISSUE TITLE
make a superuser page from which Jeff can manage accounts.

### ISSUE THREAD

**Issue by JulesChoq** [WhitmanCSCapstone/bmac-warehouse#28]
Should have links to buttons that can create accounts, reset passwords, and stuff like that

**Comment by JulesChoq** [comment]
https://firebase.google.com/docs/auth/admin/manage-users

**Comment by JulesChoq** [comment]
REMINDER: Add error messages in password change and user creation modal.

**Comment by pablofernandezcom** [comment]
Added Pablo to this issue
