### ISSUE TITLE
Add form component for shipments

### ISSUE THREAD

**Issue by blimpich** [WhitmanCSCapstone/bmac-warehouse#5]
should replicate old form component functionality for adding a new entry to the database using antd form component

**Comment by blimpich** [comment]
this is ready for deployment but it requires changing the db so when I do it it'll fuck with everyone's branches and everyone will have to rebase.

Currently working on getting forms for the rest of the pages, but shipments is ready

**Comment by JulesChoq** [comment]
@blimpich  we can close this now?

**Comment by blimpich** [comment]
@JulesChoq Yeah lets close it
