### ISSUE TITLE
Add a delete button to the bottom of each form (with functionality... obv)

### ISSUE THREAD

**Issue by blimpich** [WhitmanCSCapstone/bmac-warehouse#56]
Kinda need this, should be more straightforward once editable forms is merged in, but you'll have to look at firebase and how to delete stuff in order to make it work

**Comment by blimpich** [comment]
3b557dd484983fbe7008d158d1e3993b51f60f2c takes care of this

**Comment by JulesChoq** [comment]
still need on a few pages
