### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot set property 'customer_id' of null

### ISSUE THREAD

**Issue by pablofernandezorg** [WhitmanCSCapstone/bmac-warehouse#57]
This is happening in Reports.

**Comment by JulesChoq** [comment]
@pablofernandezorg  how do we replicate this

**Comment by pablofernandezorg** [comment]
I replicated this by either changing dates or changing the funding source mutliple times then clicking submit again.

**Comment by blimpich** [comment]
I haven't been able to replicate this. I'm closing it for now. Please reopen if you can list a clear set of steps to replicate it.
