### ISSUE TITLE
Editing receipt can corrupt data in some cases

### ISSUE THREAD

**Issue by pablofernandezorg** [WhitmanCSCapstone/bmac-warehouse#78]
If you change a product name in a receipt and click save, it changes to INVALID PROVIDER ID.

**Comment by blimpich** [comment]
How are you changing product names in receipts? receipts don't have a modal to edit and neither do providers, so I'm not sure what you did to cause this error. Providers are invalid if there is not corresponding entry in the provider table, so if you're trying to add a new provider via the shipments table then you'll get an "invalid provider id" in a shipment.

Please edit to be more descriptive

**Comment by JulesChoq** [comment]
@pablofernandezorg  @blimpich  Is this a problem?

**Comment by blimpich** [comment]
@JulesChoq I don't think this is a problem, I'm closing this for now
